// @generated by the capnpc-rust plugin to the Cap'n Proto schema compiler.
// DO NOT EDIT.
// source: schema/vissue.capnp


pub mod operation {
  #[derive(Copy, Clone)]
  pub struct Owned(());
  impl ::capnp::introspect::Introspect for Owned { fn introspect() -> ::capnp::introspect::Type { ::capnp::introspect::TypeVariant::Struct(::capnp::introspect::RawBrandedStructSchema { generic: &_private::RAW_SCHEMA, field_types: _private::get_field_types, annotation_types: _private::get_annotation_types }).into() } }
  impl ::capnp::traits::Owned for Owned { type Reader<'a> = Reader<'a>; type Builder<'a> = Builder<'a>; }
  impl ::capnp::traits::OwnedStruct for Owned { type Reader<'a> = Reader<'a>; type Builder<'a> = Builder<'a>; }
  impl ::capnp::traits::Pipelined for Owned { type Pipeline = Pipeline; }

  pub struct Reader<'a> { reader: ::capnp::private::layout::StructReader<'a> }
  impl <> ::core::marker::Copy for Reader<'_,>  {}
  impl <> ::core::clone::Clone for Reader<'_,>  {
    fn clone(&self) -> Self { *self }
  }

  impl <> ::capnp::traits::HasTypeId for Reader<'_,>  {
    const TYPE_ID: u64 = _private::TYPE_ID;
  }
  impl <'a,> ::core::convert::From<::capnp::private::layout::StructReader<'a>> for Reader<'a,>  {
    fn from(reader: ::capnp::private::layout::StructReader<'a>) -> Self {
      Self { reader,  }
    }
  }

  impl <'a,> ::core::convert::From<Reader<'a,>> for ::capnp::dynamic_value::Reader<'a>  {
    fn from(reader: Reader<'a,>) -> Self {
      Self::Struct(::capnp::dynamic_struct::Reader::new(reader.reader, ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema { generic: &_private::RAW_SCHEMA, field_types: _private::get_field_types::<>, annotation_types: _private::get_annotation_types::<>})))
    }
  }

  impl <> ::core::fmt::Debug for Reader<'_,>  {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::result::Result<(), ::core::fmt::Error> {
      core::fmt::Debug::fmt(&::core::convert::Into::<::capnp::dynamic_value::Reader<'_>>::into(*self), f)
    }
  }

  impl <'a,> ::capnp::traits::FromPointerReader<'a> for Reader<'a,>  {
    fn get_from_pointer(reader: &::capnp::private::layout::PointerReader<'a>, default: ::core::option::Option<&'a [::capnp::Word]>) -> ::capnp::Result<Self> {
      ::core::result::Result::Ok(reader.get_struct(default)?.into())
    }
  }

  impl <'a,> ::capnp::traits::IntoInternalStructReader<'a> for Reader<'a,>  {
    fn into_internal_struct_reader(self) -> ::capnp::private::layout::StructReader<'a> {
      self.reader
    }
  }

  impl <'a,> ::capnp::traits::Imbue<'a> for Reader<'a,>  {
    fn imbue(&mut self, cap_table: &'a ::capnp::private::layout::CapTable) {
      self.reader.imbue(::capnp::private::layout::CapTableReader::Plain(cap_table))
    }
  }

  impl <'a,> Reader<'a,>  {
    pub fn reborrow(&self) -> Reader<'_,> {
      Self { .. *self }
    }

    pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
      self.reader.total_size()
    }
    #[inline]
    pub fn get_cli(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
      ::capnp::traits::FromPointerReader::get_from_pointer(&self.reader.get_pointer_field(0), ::core::option::Option::None)
    }
    #[inline]
    pub fn has_cli(&self) -> bool {
      !self.reader.get_pointer_field(0).is_null()
    }
    #[inline]
    pub fn get_socket(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
      ::capnp::traits::FromPointerReader::get_from_pointer(&self.reader.get_pointer_field(1), ::core::option::Option::None)
    }
    #[inline]
    pub fn has_socket(&self) -> bool {
      !self.reader.get_pointer_field(1).is_null()
    }
    #[inline]
    pub fn get_mcp(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
      ::capnp::traits::FromPointerReader::get_from_pointer(&self.reader.get_pointer_field(2), ::core::option::Option::None)
    }
    #[inline]
    pub fn has_mcp(&self) -> bool {
      !self.reader.get_pointer_field(2).is_null()
    }
    #[inline]
    pub fn get_mutates(self) -> bool {
      self.reader.get_bool_field(0)
    }
    #[inline]
    pub fn get_note(self) -> ::capnp::Result<::capnp::text::Reader<'a>> {
      ::capnp::traits::FromPointerReader::get_from_pointer(&self.reader.get_pointer_field(3), ::core::option::Option::None)
    }
    #[inline]
    pub fn has_note(&self) -> bool {
      !self.reader.get_pointer_field(3).is_null()
    }
    #[inline]
    pub fn get_flags(self) -> ::capnp::Result<::capnp::text_list::Reader<'a>> {
      ::capnp::traits::FromPointerReader::get_from_pointer(&self.reader.get_pointer_field(4), ::core::option::Option::None)
    }
    #[inline]
    pub fn has_flags(&self) -> bool {
      !self.reader.get_pointer_field(4).is_null()
    }
  }

  pub struct Builder<'a> { builder: ::capnp::private::layout::StructBuilder<'a> }
  impl <> ::capnp::traits::HasStructSize for Builder<'_,>  {
    const STRUCT_SIZE: ::capnp::private::layout::StructSize = ::capnp::private::layout::StructSize { data: 1, pointers: 5 };
  }
  impl <> ::capnp::traits::HasTypeId for Builder<'_,>  {
    const TYPE_ID: u64 = _private::TYPE_ID;
  }
  impl <'a,> ::core::convert::From<::capnp::private::layout::StructBuilder<'a>> for Builder<'a,>  {
    fn from(builder: ::capnp::private::layout::StructBuilder<'a>) -> Self {
      Self { builder,  }
    }
  }

  impl <'a,> ::core::convert::From<Builder<'a,>> for ::capnp::dynamic_value::Builder<'a>  {
    fn from(builder: Builder<'a,>) -> Self {
      Self::Struct(::capnp::dynamic_struct::Builder::new(builder.builder, ::capnp::schema::StructSchema::new(::capnp::introspect::RawBrandedStructSchema { generic: &_private::RAW_SCHEMA, field_types: _private::get_field_types::<>, annotation_types: _private::get_annotation_types::<>})))
    }
  }

  impl <'a,> ::capnp::traits::ImbueMut<'a> for Builder<'a,>  {
    fn imbue_mut(&mut self, cap_table: &'a mut ::capnp::private::layout::CapTable) {
      self.builder.imbue(::capnp::private::layout::CapTableBuilder::Plain(cap_table))
    }
  }

  impl <'a,> ::capnp::traits::FromPointerBuilder<'a> for Builder<'a,>  {
    fn init_pointer(builder: ::capnp::private::layout::PointerBuilder<'a>, _size: u32) -> Self {
      builder.init_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE).into()
    }
    fn get_from_pointer(builder: ::capnp::private::layout::PointerBuilder<'a>, default: ::core::option::Option<&'a [::capnp::Word]>) -> ::capnp::Result<Self> {
      ::core::result::Result::Ok(builder.get_struct(<Self as ::capnp::traits::HasStructSize>::STRUCT_SIZE, default)?.into())
    }
  }

  impl <> ::capnp::traits::SetterInput<Owned<>> for Reader<'_,>  {
    fn set_pointer_builder(mut pointer: ::capnp::private::layout::PointerBuilder<'_>, value: Self, canonicalize: bool) -> ::capnp::Result<()> { pointer.set_struct(&value.reader, canonicalize) }
  }

  impl <'a,> Builder<'a,>  {
    pub fn into_reader(self) -> Reader<'a,> {
      self.builder.into_reader().into()
    }
    pub fn reborrow(&mut self) -> Builder<'_,> {
      Builder { builder: self.builder.reborrow() }
    }
    pub fn reborrow_as_reader(&self) -> Reader<'_,> {
      self.builder.as_reader().into()
    }

    pub fn total_size(&self) -> ::capnp::Result<::capnp::MessageSize> {
      self.builder.as_reader().total_size()
    }
    #[inline]
    pub fn get_cli(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
      ::capnp::traits::FromPointerBuilder::get_from_pointer(self.builder.get_pointer_field(0), ::core::option::Option::None)
    }
    #[inline]
    pub fn set_cli(&mut self, value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>)  {
      ::capnp::traits::SetterInput::set_pointer_builder(self.builder.reborrow().get_pointer_field(0), value, false).unwrap()
    }
    #[inline]
    pub fn init_cli(self, size: u32) -> ::capnp::text::Builder<'a> {
      self.builder.get_pointer_field(0).init_text(size)
    }
    #[inline]
    pub fn has_cli(&self) -> bool {
      !self.builder.is_pointer_field_null(0)
    }
    #[inline]
    pub fn get_socket(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
      ::capnp::traits::FromPointerBuilder::get_from_pointer(self.builder.get_pointer_field(1), ::core::option::Option::None)
    }
    #[inline]
    pub fn set_socket(&mut self, value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>)  {
      ::capnp::traits::SetterInput::set_pointer_builder(self.builder.reborrow().get_pointer_field(1), value, false).unwrap()
    }
    #[inline]
    pub fn init_socket(self, size: u32) -> ::capnp::text::Builder<'a> {
      self.builder.get_pointer_field(1).init_text(size)
    }
    #[inline]
    pub fn has_socket(&self) -> bool {
      !self.builder.is_pointer_field_null(1)
    }
    #[inline]
    pub fn get_mcp(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
      ::capnp::traits::FromPointerBuilder::get_from_pointer(self.builder.get_pointer_field(2), ::core::option::Option::None)
    }
    #[inline]
    pub fn set_mcp(&mut self, value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>)  {
      ::capnp::traits::SetterInput::set_pointer_builder(self.builder.reborrow().get_pointer_field(2), value, false).unwrap()
    }
    #[inline]
    pub fn init_mcp(self, size: u32) -> ::capnp::text::Builder<'a> {
      self.builder.get_pointer_field(2).init_text(size)
    }
    #[inline]
    pub fn has_mcp(&self) -> bool {
      !self.builder.is_pointer_field_null(2)
    }
    #[inline]
    pub fn get_mutates(self) -> bool {
      self.builder.get_bool_field(0)
    }
    #[inline]
    pub fn set_mutates(&mut self, value: bool)  {
      self.builder.set_bool_field(0, value);
    }
    #[inline]
    pub fn get_note(self) -> ::capnp::Result<::capnp::text::Builder<'a>> {
      ::capnp::traits::FromPointerBuilder::get_from_pointer(self.builder.get_pointer_field(3), ::core::option::Option::None)
    }
    #[inline]
    pub fn set_note(&mut self, value: impl ::capnp::traits::SetterInput<::capnp::text::Owned>)  {
      ::capnp::traits::SetterInput::set_pointer_builder(self.builder.reborrow().get_pointer_field(3), value, false).unwrap()
    }
    #[inline]
    pub fn init_note(self, size: u32) -> ::capnp::text::Builder<'a> {
      self.builder.get_pointer_field(3).init_text(size)
    }
    #[inline]
    pub fn has_note(&self) -> bool {
      !self.builder.is_pointer_field_null(3)
    }
    #[inline]
    pub fn get_flags(self) -> ::capnp::Result<::capnp::text_list::Builder<'a>> {
      ::capnp::traits::FromPointerBuilder::get_from_pointer(self.builder.get_pointer_field(4), ::core::option::Option::None)
    }
    #[inline]
    pub fn set_flags(&mut self, value: impl ::capnp::traits::SetterInput<::capnp::text_list::Owned>) -> ::capnp::Result<()> {
      ::capnp::traits::SetterInput::set_pointer_builder(self.builder.reborrow().get_pointer_field(4), value, false)
    }
    #[inline]
    pub fn init_flags(self, size: u32) -> ::capnp::text_list::Builder<'a> {
      ::capnp::traits::FromPointerBuilder::init_pointer(self.builder.get_pointer_field(4), size)
    }
    #[inline]
    pub fn has_flags(&self) -> bool {
      !self.builder.is_pointer_field_null(4)
    }
  }

  pub struct Pipeline { _typeless: ::capnp::any_pointer::Pipeline }
  impl ::capnp::capability::FromTypelessPipeline for Pipeline {
    fn new(typeless: ::capnp::any_pointer::Pipeline) -> Self {
      Self { _typeless: typeless,  }
    }
  }
  impl Pipeline  {
  }
  mod _private {
    pub static ENCODED_NODE: [::capnp::Word; 113] = [
      ::capnp::word(0, 0, 0, 0, 6, 0, 6, 0),
      ::capnp::word(240, 122, 105, 57, 206, 250, 95, 199),
      ::capnp::word(20, 0, 0, 0, 1, 0, 1, 0),
      ::capnp::word(147, 155, 249, 219, 71, 199, 231, 161),
      ::capnp::word(5, 0, 7, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(36, 5, 0, 0, 132, 10, 0, 0),
      ::capnp::word(21, 0, 0, 0, 242, 0, 0, 0),
      ::capnp::word(33, 0, 0, 0, 7, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(29, 0, 0, 0, 87, 1, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(115, 99, 104, 101, 109, 97, 47, 118),
      ::capnp::word(105, 115, 115, 117, 101, 46, 99, 97),
      ::capnp::word(112, 110, 112, 58, 79, 112, 101, 114),
      ::capnp::word(97, 116, 105, 111, 110, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 1, 0, 1, 0),
      ::capnp::word(24, 0, 0, 0, 3, 0, 4, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 1, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(153, 0, 0, 0, 34, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(148, 0, 0, 0, 3, 0, 1, 0),
      ::capnp::word(160, 0, 0, 0, 2, 0, 1, 0),
      ::capnp::word(1, 0, 0, 0, 1, 0, 0, 0),
      ::capnp::word(0, 0, 1, 0, 1, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(157, 0, 0, 0, 58, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(152, 0, 0, 0, 3, 0, 1, 0),
      ::capnp::word(164, 0, 0, 0, 2, 0, 1, 0),
      ::capnp::word(2, 0, 0, 0, 2, 0, 0, 0),
      ::capnp::word(0, 0, 1, 0, 2, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(161, 0, 0, 0, 34, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(156, 0, 0, 0, 3, 0, 1, 0),
      ::capnp::word(168, 0, 0, 0, 2, 0, 1, 0),
      ::capnp::word(3, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 1, 0, 3, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(165, 0, 0, 0, 66, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(160, 0, 0, 0, 3, 0, 1, 0),
      ::capnp::word(172, 0, 0, 0, 2, 0, 1, 0),
      ::capnp::word(4, 0, 0, 0, 3, 0, 0, 0),
      ::capnp::word(0, 0, 1, 0, 4, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(169, 0, 0, 0, 42, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(164, 0, 0, 0, 3, 0, 1, 0),
      ::capnp::word(176, 0, 0, 0, 2, 0, 1, 0),
      ::capnp::word(5, 0, 0, 0, 4, 0, 0, 0),
      ::capnp::word(0, 0, 1, 0, 5, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(173, 0, 0, 0, 50, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(168, 0, 0, 0, 3, 0, 1, 0),
      ::capnp::word(196, 0, 0, 0, 2, 0, 1, 0),
      ::capnp::word(99, 108, 105, 0, 0, 0, 0, 0),
      ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(115, 111, 99, 107, 101, 116, 0, 0),
      ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(109, 99, 112, 0, 0, 0, 0, 0),
      ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(109, 117, 116, 97, 116, 101, 115, 0),
      ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(110, 111, 116, 101, 0, 0, 0, 0),
      ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(102, 108, 97, 103, 115, 0, 0, 0),
      ::capnp::word(14, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 3, 0, 1, 0),
      ::capnp::word(12, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(14, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
      ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ];
    pub fn get_field_types(index: u16) -> ::capnp::introspect::Type {
      match index {
        0 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
        1 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
        2 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
        3 => <bool as ::capnp::introspect::Introspect>::introspect(),
        4 => <::capnp::text::Owned as ::capnp::introspect::Introspect>::introspect(),
        5 => <::capnp::text_list::Owned as ::capnp::introspect::Introspect>::introspect(),
        _ => ::capnp::introspect::panic_invalid_field_index(index),
      }
    }
    pub fn get_annotation_types(child_index: Option<u16>, index: u32) -> ::capnp::introspect::Type {
      ::capnp::introspect::panic_invalid_annotation_indices(child_index, index)
    }
    pub static RAW_SCHEMA: ::capnp::introspect::RawStructSchema = ::capnp::introspect::RawStructSchema {
      encoded_node: &ENCODED_NODE,
      nonunion_members: NONUNION_MEMBERS,
      members_by_discriminant: MEMBERS_BY_DISCRIMINANT,
      members_by_name: MEMBERS_BY_NAME,
    };
    pub static NONUNION_MEMBERS : &[u16] = &[0,1,2,3,4,5];
    pub static MEMBERS_BY_DISCRIMINANT : &[u16] = &[];
    pub static MEMBERS_BY_NAME : &[u16] = &[0,5,2,3,4,1];
    pub const TYPE_ID: u64 = 0xc75f_face_3969_7af0;
  }
}
pub static OPERATIONS: ::capnp::constant::Reader<::capnp::struct_list::Owned<crate::vissue_capnp::operation::Owned>> = {
  static WORDS: [::capnp::Word; 201] = [
    ::capnp::word(1, 0, 0, 0, 23, 2, 0, 0),
    ::capnp::word(44, 0, 0, 0, 1, 0, 5, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(1, 1, 0, 0, 58, 0, 0, 0),
    ::capnp::word(1, 1, 0, 0, 106, 0, 0, 0),
    ::capnp::word(5, 1, 0, 0, 114, 0, 0, 0),
    ::capnp::word(9, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(9, 1, 0, 0, 78, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(89, 1, 0, 0, 58, 0, 0, 0),
    ::capnp::word(89, 1, 0, 0, 106, 0, 0, 0),
    ::capnp::word(93, 1, 0, 0, 114, 0, 0, 0),
    ::capnp::word(97, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(97, 1, 0, 0, 54, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(145, 1, 0, 0, 50, 0, 0, 0),
    ::capnp::word(145, 1, 0, 0, 98, 0, 0, 0),
    ::capnp::word(149, 1, 0, 0, 106, 0, 0, 0),
    ::capnp::word(153, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(153, 1, 0, 0, 14, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(153, 1, 0, 0, 42, 0, 0, 0),
    ::capnp::word(153, 1, 0, 0, 90, 0, 0, 0),
    ::capnp::word(157, 1, 0, 0, 98, 0, 0, 0),
    ::capnp::word(161, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(161, 1, 0, 0, 6, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(153, 1, 0, 0, 58, 0, 0, 0),
    ::capnp::word(153, 1, 0, 0, 106, 0, 0, 0),
    ::capnp::word(157, 1, 0, 0, 114, 0, 0, 0),
    ::capnp::word(161, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(161, 1, 0, 0, 22, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(169, 1, 0, 0, 58, 0, 0, 0),
    ::capnp::word(169, 1, 0, 0, 106, 0, 0, 0),
    ::capnp::word(173, 1, 0, 0, 114, 0, 0, 0),
    ::capnp::word(177, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(177, 1, 0, 0, 14, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(177, 1, 0, 0, 58, 0, 0, 0),
    ::capnp::word(177, 1, 0, 0, 106, 0, 0, 0),
    ::capnp::word(181, 1, 0, 0, 114, 0, 0, 0),
    ::capnp::word(185, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(185, 1, 0, 0, 30, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(201, 1, 0, 0, 66, 0, 0, 0),
    ::capnp::word(201, 1, 0, 0, 114, 0, 0, 0),
    ::capnp::word(205, 1, 0, 0, 122, 0, 0, 0),
    ::capnp::word(209, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(209, 1, 0, 0, 6, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(201, 1, 0, 0, 42, 0, 0, 0),
    ::capnp::word(201, 1, 0, 0, 90, 0, 0, 0),
    ::capnp::word(205, 1, 0, 0, 98, 0, 0, 0),
    ::capnp::word(209, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(209, 1, 0, 0, 14, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(209, 1, 0, 0, 42, 0, 0, 0),
    ::capnp::word(209, 1, 0, 0, 90, 0, 0, 0),
    ::capnp::word(213, 1, 0, 0, 98, 0, 0, 0),
    ::capnp::word(217, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(217, 1, 0, 0, 14, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(217, 1, 0, 0, 82, 0, 0, 0),
    ::capnp::word(221, 1, 0, 0, 130, 0, 0, 0),
    ::capnp::word(225, 1, 0, 0, 10, 0, 0, 0),
    ::capnp::word(225, 1, 0, 0, 106, 2, 0, 0),
    ::capnp::word(5, 2, 0, 0, 22, 0, 0, 0),
    ::capnp::word(99, 114, 101, 97, 116, 101, 0, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 99, 114),
    ::capnp::word(101, 97, 116, 101, 0, 0, 0, 0),
    ::capnp::word(118, 105, 115, 115, 117, 101, 95, 99),
    ::capnp::word(114, 101, 97, 116, 101, 0, 0, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(33, 0, 0, 0, 66, 0, 0, 0),
    ::capnp::word(33, 0, 0, 0, 74, 0, 0, 0),
    ::capnp::word(37, 0, 0, 0, 42, 0, 0, 0),
    ::capnp::word(37, 0, 0, 0, 42, 0, 0, 0),
    ::capnp::word(37, 0, 0, 0, 58, 0, 0, 0),
    ::capnp::word(37, 0, 0, 0, 42, 0, 0, 0),
    ::capnp::word(37, 0, 0, 0, 82, 0, 0, 0),
    ::capnp::word(41, 0, 0, 0, 74, 0, 0, 0),
    ::capnp::word(45, 0, 0, 0, 82, 0, 0, 0),
    ::capnp::word(112, 114, 111, 106, 101, 99, 116, 0),
    ::capnp::word(112, 114, 105, 111, 114, 105, 116, 121),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(116, 121, 112, 101, 0, 0, 0, 0),
    ::capnp::word(116, 97, 103, 115, 0, 0, 0, 0),
    ::capnp::word(112, 97, 114, 101, 110, 116, 0, 0),
    ::capnp::word(98, 111, 100, 121, 0, 0, 0, 0),
    ::capnp::word(98, 111, 100, 121, 45, 102, 105, 108),
    ::capnp::word(101, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(100, 101, 97, 100, 108, 105, 110, 101),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(115, 99, 104, 101, 100, 117, 108, 101),
    ::capnp::word(100, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(117, 112, 100, 97, 116, 101, 0, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 117, 112),
    ::capnp::word(100, 97, 116, 101, 0, 0, 0, 0),
    ::capnp::word(118, 105, 115, 115, 117, 101, 95, 117),
    ::capnp::word(112, 100, 97, 116, 101, 0, 0, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(21, 0, 0, 0, 50, 0, 0, 0),
    ::capnp::word(21, 0, 0, 0, 74, 0, 0, 0),
    ::capnp::word(25, 0, 0, 0, 50, 0, 0, 0),
    ::capnp::word(25, 0, 0, 0, 66, 0, 0, 0),
    ::capnp::word(25, 0, 0, 0, 74, 0, 0, 0),
    ::capnp::word(29, 0, 0, 0, 58, 0, 0, 0),
    ::capnp::word(115, 116, 97, 116, 101, 0, 0, 0),
    ::capnp::word(112, 114, 105, 111, 114, 105, 116, 121),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(98, 108, 111, 99, 107, 0, 0, 0),
    ::capnp::word(117, 110, 98, 108, 111, 99, 107, 0),
    ::capnp::word(105, 102, 45, 115, 116, 97, 116, 101),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(105, 102, 45, 103, 101, 110, 0, 0),
    ::capnp::word(99, 108, 97, 105, 109, 0, 0, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 99, 108),
    ::capnp::word(97, 105, 109, 0, 0, 0, 0, 0),
    ::capnp::word(118, 105, 115, 115, 117, 101, 95, 99),
    ::capnp::word(108, 97, 105, 109, 0, 0, 0, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 50, 0, 0, 0),
    ::capnp::word(102, 111, 114, 99, 101, 0, 0, 0),
    ::capnp::word(110, 111, 116, 101, 0, 0, 0, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 110, 111),
    ::capnp::word(116, 101, 0, 0, 0, 0, 0, 0),
    ::capnp::word(118, 105, 115, 115, 117, 101, 95, 110),
    ::capnp::word(111, 116, 101, 0, 0, 0, 0, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(97, 112, 112, 101, 110, 100, 0, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 97, 112),
    ::capnp::word(112, 101, 110, 100, 0, 0, 0, 0),
    ::capnp::word(118, 105, 115, 115, 117, 101, 95, 97),
    ::capnp::word(112, 112, 101, 110, 100, 0, 0, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(5, 0, 0, 0, 42, 0, 0, 0),
    ::capnp::word(5, 0, 0, 0, 42, 0, 0, 0),
    ::capnp::word(116, 101, 120, 116, 0, 0, 0, 0),
    ::capnp::word(102, 105, 108, 101, 0, 0, 0, 0),
    ::capnp::word(114, 101, 102, 105, 108, 101, 0, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 114, 101),
    ::capnp::word(102, 105, 108, 101, 0, 0, 0, 0),
    ::capnp::word(118, 105, 115, 115, 117, 101, 95, 114),
    ::capnp::word(101, 102, 105, 108, 101, 0, 0, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 26, 0, 0, 0),
    ::capnp::word(116, 111, 0, 0, 0, 0, 0, 0),
    ::capnp::word(114, 101, 106, 101, 99, 116, 0, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 114, 101),
    ::capnp::word(106, 101, 99, 116, 0, 0, 0, 0),
    ::capnp::word(118, 105, 115, 115, 117, 101, 95, 114),
    ::capnp::word(101, 106, 101, 99, 116, 0, 0, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(9, 0, 0, 0, 26, 0, 0, 0),
    ::capnp::word(9, 0, 0, 0, 66, 0, 0, 0),
    ::capnp::word(9, 0, 0, 0, 58, 0, 0, 0),
    ::capnp::word(116, 111, 0, 0, 0, 0, 0, 0),
    ::capnp::word(112, 114, 111, 106, 101, 99, 116, 0),
    ::capnp::word(114, 101, 97, 115, 111, 110, 0, 0),
    ::capnp::word(114, 101, 115, 111, 108, 118, 101, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 114, 101),
    ::capnp::word(115, 111, 108, 118, 101, 0, 0, 0),
    ::capnp::word(118, 105, 115, 115, 117, 101, 95, 114),
    ::capnp::word(101, 115, 111, 108, 118, 101, 0, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(118, 111, 116, 101, 0, 0, 0, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 118, 111),
    ::capnp::word(116, 101, 0, 0, 0, 0, 0, 0),
    ::capnp::word(118, 105, 115, 115, 117, 101, 95, 118),
    ::capnp::word(111, 116, 101, 0, 0, 0, 0, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 34, 0, 0, 0),
    ::capnp::word(102, 111, 114, 0, 0, 0, 0, 0),
    ::capnp::word(102, 111, 108, 100, 0, 0, 0, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 102, 111),
    ::capnp::word(108, 100, 0, 0, 0, 0, 0, 0),
    ::capnp::word(118, 105, 115, 115, 117, 101, 95, 102),
    ::capnp::word(111, 108, 100, 0, 0, 0, 0, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(1, 0, 0, 0, 66, 0, 0, 0),
    ::capnp::word(112, 114, 111, 106, 101, 99, 116, 0),
    ::capnp::word(110, 111, 114, 109, 97, 108, 105, 122),
    ::capnp::word(101, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(105, 115, 115, 117, 101, 47, 110, 111),
    ::capnp::word(114, 109, 97, 108, 105, 122, 101, 0),
    ::capnp::word(0, 0, 0, 0, 0, 0, 0, 0),
    ::capnp::word(110, 111, 32, 116, 111, 111, 108, 58),
    ::capnp::word(32, 114, 101, 119, 114, 105, 116, 105),
    ::capnp::word(110, 103, 32, 101, 118, 101, 114, 121),
    ::capnp::word(32, 104, 101, 97, 100, 105, 110, 103),
    ::capnp::word(32, 105, 110, 32, 97, 32, 99, 111),
    ::capnp::word(114, 112, 117, 115, 32, 105, 115, 32),
    ::capnp::word(110, 111, 116, 32, 97, 32, 116, 104),
    ::capnp::word(105, 110, 103, 32, 116, 111, 32, 104),
    ::capnp::word(97, 110, 100, 32, 97, 110, 32, 97),
    ::capnp::word(103, 101, 110, 116, 0, 0, 0, 0),
    ::capnp::word(5, 0, 0, 0, 66, 0, 0, 0),
    ::capnp::word(5, 0, 0, 0, 66, 0, 0, 0),
    ::capnp::word(112, 114, 111, 106, 101, 99, 116, 0),
    ::capnp::word(100, 114, 121, 45, 114, 117, 110, 0),
  ];
  ::capnp::constant::Reader {
    phantom: ::core::marker::PhantomData,
    words: &WORDS,
  }
};
