//! Command-line behaviour, exercised through the built binary.

use std::fs;
use std::path::Path;
use std::process::Command;

#[cfg(not(unix))]
#[test]
fn serve_is_unix_only() {
    let out = Command::new(env!("CARGO_BIN_EXE_vissue"))
        .arg("serve")
        .output()
        .expect("run vissue");
    assert!(!out.status.success());
    assert!(
        String::from_utf8_lossy(&out.stderr).contains("Unix-only"),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
}

fn fixture_root() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixture_vault")
}

fn vissue(args: &[&str]) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_vissue"))
        .args(["--root", fixture_root().to_str().unwrap()])
        .args(args)
        .output()
        .expect("run vissue")
}

fn stdout(out: &std::process::Output) -> String {
    String::from_utf8(out.stdout.clone()).unwrap()
}

#[test]
fn projects_lists_the_fixture_projects() {
    let out = vissue(&["projects"]);
    assert!(out.status.success());
    assert_eq!(stdout(&out), "atlas\nbeacon\n");
}

#[test]
fn count_and_list_accept_both_project_flags() {
    assert_eq!(stdout(&vissue(&["count", "-P", "atlas"])), "4\n");
    assert_eq!(stdout(&vissue(&["count", "-p", "atlas"])), "4\n");
    assert_eq!(stdout(&vissue(&["count", "--project", "atlas"])), "4\n");
    let listed = stdout(&vissue(&["list", "-P", "atlas"]));
    assert_eq!(listed.lines().count(), 4, "{listed}");
    assert!(listed.contains("atlas-1a2b"), "{listed}");
}

#[test]
fn export_emits_one_json_object_per_line() {
    let out = vissue(&["export", "-P", "beacon"]);
    assert!(out.status.success());
    let text = stdout(&out);
    assert_eq!(text.lines().count(), 2, "{text}");
    for line in text.lines() {
        let row: serde_json::Value = serde_json::from_str(line).unwrap();
        assert_eq!(row["project"], "beacon");
    }
}

#[test]
fn check_exits_zero_on_the_fixture() {
    let out = vissue(&["check"]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(stdout(&out).contains("0 error(s), 0 warning(s)"));
}

#[test]
fn show_json_returns_an_object() {
    let out = vissue(&["show", "atlas-2c3d", "--json"]);
    assert!(out.status.success());
    let row: serde_json::Value = serde_json::from_str(&stdout(&out)).unwrap();
    assert_eq!(row["id"], "atlas-2c3d");
    assert_eq!(row["parent"], "atlas-1a2b");
}

#[test]
fn mirror_writes_a_file_and_reports_the_path() {
    let dir = tempfile::tempdir().unwrap();
    let target = dir.path().join("nested/mirror.org");
    let out = vissue(&["mirror", "-P", "atlas", "--out", target.to_str().unwrap()]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(stdout(&out).starts_with("wrote "));
    let text = fs::read_to_string(&target).unwrap();
    assert!(
        text.contains("# MIRROR: generated by `vissue mirror`"),
        "{text}"
    );
    assert!(text.contains("* atlas"), "{text}");
    assert!(!text.contains("* beacon"), "{text}");
}

#[test]
fn mirror_writes_to_stdout_on_a_dash() {
    let out = vissue(&["mirror", "--out", "-", "--format", "markdown"]);
    assert!(out.status.success());
    let text = stdout(&out);
    assert!(text.starts_with("# vissue mirror"), "{text}");
    assert!(text.contains("## atlas"), "{text}");
    assert!(text.contains("## beacon"), "{text}");
}

#[test]
fn an_unknown_mirror_format_fails_loudly() {
    let out = vissue(&["mirror", "--out", "-", "--format", "pdf"]);
    assert!(!out.status.success());
    assert!(String::from_utf8_lossy(&out.stderr).contains("unknown format"));
}

#[test]
fn whoami_prints_the_identity_a_claim_would_record() {
    let out = vissue(&["whoami"]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let text = stdout(&out);
    assert!(!text.trim().is_empty(), "no identity printed");
}

#[test]
fn tui_help_names_offline() {
    let out = vissue(&["tui", "--help"]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let text = stdout(&out);
    assert!(text.contains("--offline"), "{text}");
    assert!(text.contains("Never attach"), "{text}");
}

#[test]
fn hud_help_names_rofi_and_iced() {
    let out = vissue(&["hud", "--help"]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let text = stdout(&out);
    assert!(text.contains("--mode"), "{text}");
    assert!(text.contains("rofi"), "{text}");
    assert!(text.contains("--rofi"), "{text}");
    assert!(text.contains("--iced"), "{text}");
    assert!(text.contains("--toggle"), "{text}");
}

#[test]
fn iced_hud_without_binary_exits_127() {
    let out = Command::new(env!("CARGO_BIN_EXE_vissue"))
        .args(["--root", fixture_root().to_str().unwrap(), "hud"])
        .env("VISSUE_HUD_BIN", "/nonexistent/vissue-hud")
        .env("PATH", "/nonexistent")
        .output()
        .expect("run vissue hud --iced");
    assert_eq!(out.status.code(), Some(127));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("cargo install vissue-hud"), "{err}");
}

#[test]
fn hud_missing_override_bin_exits_127() {
    let out = Command::new(env!("CARGO_BIN_EXE_vissue"))
        .args(["--root", fixture_root().to_str().unwrap(), "hud", "--iced"])
        .env("VISSUE_HUD_BIN", "/nonexistent/vissue-hud")
        .output()
        .expect("run vissue hud --iced");
    assert_eq!(out.status.code(), Some(127));
    let err = String::from_utf8_lossy(&out.stderr);
    assert!(err.contains("cargo install vissue-hud"), "{err}");
}

#[cfg(not(unix))]
#[test]
fn tui_without_offline_is_unix_only() {
    let out = vissue(&["tui"]);
    assert!(!out.status.success());
    assert!(
        String::from_utf8_lossy(&out.stderr).contains("Unix-only"),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
}

#[cfg(not(unix))]
#[test]
fn hud_without_offline_is_unix_only() {
    let out = vissue(&["hud"]);
    assert!(!out.status.success());
    assert!(
        String::from_utf8_lossy(&out.stderr).contains("Unix-only"),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
}

#[test]
fn identity_reports_the_resolved_binary_root_and_prefix() {
    // `identity` answers the wrapper's old question, "which binary and which
    // tracker", and is distinct from `whoami`, which names the claimant.
    let text = stdout(&vissue(&["identity"]));
    assert!(text.contains("prefix: Software"), "{text}");
    assert!(text.contains("prefix=Software"), "{text}");
    assert!(text.contains("fixture_vault"), "{text}");
    assert!(text.contains("binary:"), "{text}");
}

#[test]
fn the_environment_can_name_the_claiming_identity() {
    let out = Command::new(env!("CARGO_BIN_EXE_vissue"))
        .args(["--root", fixture_root().to_str().unwrap()])
        .env("VISSUE_AGENT", "grind-worker-3")
        .arg("whoami")
        .output()
        .expect("run vissue");
    assert_eq!(
        String::from_utf8(out.stdout).unwrap().trim(),
        "grind-worker-3"
    );
}

#[test]
fn a_create_and_update_cycle_works_in_a_temporary_root() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().to_str().unwrap();
    let run = |args: &[&str]| {
        Command::new(env!("CARGO_BIN_EXE_vissue"))
            .args(["--root", root])
            .args(args)
            .output()
            .expect("run vissue")
    };

    let created = run(&["create", "-P", "demo", "--quiet", "first task"]);
    assert!(
        created.status.success(),
        "{}",
        String::from_utf8_lossy(&created.stderr)
    );
    let id = String::from_utf8(created.stdout)
        .unwrap()
        .trim()
        .to_string();
    assert!(id.starts_with("demo-"), "{id}");

    let updated = run(&["update", &id, "--state", "STARTED"]);
    assert!(updated.status.success());
    assert!(String::from_utf8_lossy(&updated.stdout).contains("state TODO -> STARTED"));

    let shown = run(&["show", &id]);
    assert!(String::from_utf8_lossy(&shown.stdout).contains("State:    STARTED"));
    assert_eq!(
        String::from_utf8_lossy(&run(&["count", "--ready"]).stdout),
        "1\n"
    );
}

#[test]
fn the_root_may_come_from_the_environment() {
    let out = Command::new(env!("CARGO_BIN_EXE_vissue"))
        .env("VISSUE_ROOT", fixture_root())
        .arg("projects")
        .output()
        .expect("run vissue");
    assert_eq!(String::from_utf8(out.stdout).unwrap(), "atlas\nbeacon\n");
}

#[test]
fn the_shared_issue_root_environment_is_supported() {
    let out = Command::new(env!("CARGO_BIN_EXE_vissue"))
        .env_remove("VISSUE_ROOT")
        .env("ISSUE_ROOT", fixture_root())
        .arg("projects")
        .output()
        .expect("run vissue");
    assert_eq!(String::from_utf8(out.stdout).unwrap(), "atlas\nbeacon\n");
}

#[test]
fn the_read_only_command_surface_dispatches_against_the_fixture() {
    let cases: &[(&[&str], &str)] = &[
        (&["list", "--json"], "\"id\": \"atlas-3e4f\""),
        (
            &["show", "atlas-1a2b"],
            "Title:    Parse the manifest header",
        ),
        (&["ready", "--json"], "\"id\": \"atlas-1a2b\""),
        (&["claims"], "fixture-agent"),
        (&["agenda", "--days", "5000"], "beacon-5j6k"),
        (&["hygiene", "--stale-days", "1"], "stale_claims=1"),
        (&["waiting-on", "atlas-1a2b"], "atlas-3e4f"),
        (
            &["body-excerpt", "atlas-1a2b"],
            "* STARTED [#A] Parse the manifest header",
        ),
        (&["search", "parser"], "atlas-1a2b"),
        (&["children", "atlas-1a2b"], "atlas-2c3d"),
        (&["ancestors", "atlas-3e4f", "--depth", "3"], "1 atlas-1a2b"),
        (&["impact", "atlas-1a2b", "--depth", "3"], "1 atlas-3e4f"),
        (
            &["related", "atlas-1a2b", "--format", "org"],
            "[[id:atlas-2c3d]",
        ),
        (&["stale", "--days", "1"], "beacon-5j6k"),
        (&["count", "--state", "TODO"], "2\n"),
        (
            &["tree", "atlas-1a2b", "--format", "dot"],
            "digraph vissue_tree",
        ),
        (&["cycles"], "no cycles"),
        (&["graph", "--project", "atlas"], "digraph vissue_graph"),
        (&["backlinks", "atlas-1a2b"], "atlas-2c3d"),
        (&["roadmap", "--project", "atlas"], "## atlas"),
        (&["digest", "--json"], "\"issues\": 6"),
        (&["events", "--since", "0"], "generation=0 since=0 count=0"),
        (&["gen"], "0\n"),
    ];

    for (args, expected) in cases {
        let out = vissue(args);
        assert!(
            out.status.success(),
            "command {args:?} failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        let text = stdout(&out);
        assert!(
            text.contains(expected),
            "command {args:?} did not contain {expected:?}: {text}"
        );
    }
}

/// `vissue export | head` closes the pipe once it has enough. The output has
/// to be larger than a pipe buffer for the writer to still be writing when
/// that happens, so this builds a corpus rather than using the fixture.
#[test]
fn a_reader_that_closes_the_pipe_is_not_a_failure() {
    use std::io::Read as _;
    use std::process::Stdio;

    let dir = tempfile::tempdir().unwrap();
    let root = dir.path().to_str().unwrap().to_string();
    for i in 0..400 {
        let out = Command::new(env!("CARGO_BIN_EXE_vissue"))
            .args(["--root", &root, "q", "-p", "demo"])
            .arg(format!(
                "issue {i} with a title long enough that four hundred of them exceed a pipe buffer"
            ))
            .output()
            .expect("run vissue");
        assert!(out.status.success());
    }

    let mut child = Command::new(env!("CARGO_BIN_EXE_vissue"))
        .args(["--root", &root, "export"])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("run vissue");

    // Read one line, then drop the pipe while the writer is mid-corpus.
    let mut stdout = child.stdout.take().unwrap();
    let mut first = [0u8; 64];
    stdout.read_exact(&mut first).unwrap();
    drop(stdout);

    let out = child.wait_with_output().expect("wait for vissue");
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(out.status.success(), "exited {:?}: {stderr}", out.status);
    assert!(stderr.is_empty(), "{stderr}");
}

/// The one command that replaces reading the file by hand.
///
/// Recovering an issue's text used to mean parsing `path:start-end` out of
/// `show` and running `sed` over the org file, because `show` printed the
/// range and stopped.
#[test]
fn show_org_writes_the_whole_heading() {
    let out = vissue(&["show", "--org", "atlas-1a2b"]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let text = stdout(&out);
    assert!(text.starts_with("* STARTED [#A]"), "{text}");
    assert!(text.contains(":ID:         atlas-1a2b"), "{text}");
    assert!(
        text.contains(":LOGBOOK:"),
        "the notes travel with it: {text}"
    );
    assert!(
        text.contains("Scope: read the header block"),
        "the body travels with it: {text}"
    );
    // Nothing but the heading, so the output can be redirected into a file.
    assert!(!text.contains("File:"), "{text}");
    assert!(!text.contains("excerpt"), "{text}");
}

#[test]
fn show_prints_the_body_and_json_carries_it() {
    let text = stdout(&vissue(&["show", "atlas-2c3d"]));
    assert!(text.contains("Body:"), "{text}");
    assert!(text.contains("Scope: one row per parsed record"), "{text}");

    let row: serde_json::Value =
        serde_json::from_str(&stdout(&vissue(&["show", "atlas-2c3d", "--json"]))).unwrap();
    assert!(
        row["body"]
            .as_str()
            .unwrap()
            .contains("one row per parsed record"),
        "{row}"
    );
}

#[test]
fn show_org_and_json_are_not_asked_for_together() {
    let out = vissue(&["show", "--org", "--json", "atlas-1a2b"]);
    assert!(!out.status.success(), "{}", stdout(&out));
}

/// Recording a worker's report, the return half of handing work out.
#[test]
fn append_reads_a_file_and_stdin() {
    let dir = tempfile::tempdir().unwrap();
    let root = dir.path();
    std::fs::create_dir_all(root.join("Software")).unwrap();
    let mk = |args: &[&str]| -> std::process::Output {
        let mut argv = vec!["--root", root.to_str().unwrap()];
        argv.extend_from_slice(args);
        Command::new(env!("CARGO_BIN_EXE_vissue"))
            .args(argv)
            .output()
            .unwrap()
    };
    let id = String::from_utf8_lossy(
        &mk(&["create", "-p", "atlas", "--quiet", "Streaming exporter"]).stdout,
    )
    .trim()
    .to_string();

    let report = dir.path().join("SUMMARY.md");
    std::fs::write(&report, "## What changed\n\n* took a Read\n").unwrap();
    let out = mk(&["append", &id, "--file", report.to_str().unwrap()]);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );

    let shown = String::from_utf8_lossy(&mk(&["show", &id]).stdout).to_string();
    assert!(shown.contains("## What changed"), "{shown}");
    assert!(shown.contains("took a Read"), "{shown}");

    // --text is the same thing without a file.
    assert!(mk(&["append", &id, "--text", "second pass"])
        .status
        .success());
    let shown = String::from_utf8_lossy(&mk(&["show", &id]).stdout).to_string();
    assert!(shown.contains("second pass"), "{shown}");

    // The tracker still reads back cleanly after markdown went in.
    let check = mk(&["check"]);
    assert!(
        check.status.success(),
        "{}",
        String::from_utf8_lossy(&check.stdout)
    );

    // Neither source given is an error, not an empty append.
    assert!(!mk(&["append", &id]).status.success());
}
