//! A read-only projection of selected projects into a single shareable file.
//!
//! The mirror exists so a collaborator who cannot reach the tracker still sees
//! the backlog. It carries a banner naming it as generated output, because the
//! next run overwrites it and hand edits are lost.

use anyhow::{bail, Result};
use std::fmt::Write as _;

use crate::config::Layout;
use crate::model::{today_inactive_bracket, IssueHeading, TODO_HEADER};
use crate::store::{list_projects, IssueDoc};

/// Body lines carried into the projection before it is cut short.
pub const BODY_LINES: usize = 12;

const BANNER: &str =
    "MIRROR: generated by `vissue mirror`. Read-only projection; edits here are overwritten.";

/// Output shape for [`render`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Format {
    Org,
    Markdown,
}

impl Format {
    pub fn parse(s: &str) -> Result<Self> {
        match s {
            "org" => Ok(Format::Org),
            "markdown" | "md" => Ok(Format::Markdown),
            other => bail!("unknown format {other:?}; allowed: org, markdown"),
        }
    }
}

/// Project the named projects into one document. An empty `projects` list
/// covers every project in the layout.
pub fn render(
    layout: &Layout,
    projects: &[String],
    format: Format,
    state_filter: Option<&str>,
) -> Result<String> {
    let selected: Vec<String> = if projects.is_empty() {
        list_projects(layout)?
    } else {
        let mut v = projects.to_vec();
        v.sort();
        v.dedup();
        v
    };

    let mut out = String::new();
    match format {
        Format::Org => {
            writeln!(out, "#+TITLE: vissue mirror")?;
            writeln!(out, "#+DATE: {}", today_inactive_bracket())?;
            writeln!(out, "#+FILETAGS: :vissue:mirror:")?;
            writeln!(out, "{TODO_HEADER}")?;
            writeln!(out, "# {BANNER}")?;
            writeln!(out, "# Projects: {}", selected.join(", "))?;
            writeln!(out)?;
        }
        Format::Markdown => {
            writeln!(out, "# vissue mirror")?;
            writeln!(out)?;
            writeln!(out, "_{BANNER}_")?;
            writeln!(out)?;
            writeln!(
                out,
                "Generated {} for: {}",
                today_inactive_bracket(),
                selected.join(", ")
            )?;
            writeln!(out)?;
        }
    }

    for project in &selected {
        let path = layout.project_issues_path(project);
        let doc = IssueDoc::parse_file(project, &path)?;
        let mut headings: Vec<&IssueHeading> = doc
            .headings
            .iter()
            .filter(|h| state_filter.map(|s| h.state == s).unwrap_or(true))
            .collect();
        headings.sort_by(|a, b| {
            a.priority
                .cmp(&b.priority)
                .then_with(|| a.state.cmp(&b.state))
                .then_with(|| a.id.cmp(&b.id))
        });
        if headings.is_empty() {
            continue;
        }
        match format {
            Format::Org => {
                writeln!(out, "* {project}")?;
                for h in headings {
                    render_org_issue(&mut out, h)?;
                }
            }
            Format::Markdown => {
                writeln!(out, "## {project}")?;
                writeln!(out)?;
                for h in headings {
                    render_markdown_issue(&mut out, h)?;
                }
            }
        }
    }
    Ok(out)
}

fn render_org_issue(out: &mut String, h: &IssueHeading) -> Result<()> {
    writeln!(out, "** {} [#{}] {}", h.state, h.priority, h.title)?;
    writeln!(out, ":PROPERTIES:")?;
    writeln!(out, ":ID:         {}", h.id)?;
    for key in ["PARENT", "BLOCKED_BY", "TAGS", "DEADLINE", "TYPE"] {
        if let Some(val) = h.properties.get(key) {
            writeln!(out, ":{key}: {val}")?;
        }
    }
    writeln!(out, ":END:")?;
    let body = compact_body(&h.body);
    if !body.is_empty() {
        writeln!(out)?;
        writeln!(out, "{body}")?;
    }
    Ok(())
}

fn render_markdown_issue(out: &mut String, h: &IssueHeading) -> Result<()> {
    writeln!(out, "### {} [#{}] {}", h.state, h.priority, h.title)?;
    writeln!(out)?;
    writeln!(out, "- id: `{}`", h.id)?;
    for key in ["PARENT", "BLOCKED_BY", "TAGS", "DEADLINE", "TYPE"] {
        if let Some(val) = h.properties.get(key) {
            writeln!(out, "- {}: {}", key.to_lowercase(), val)?;
        }
    }
    let body = compact_body(&h.body);
    if !body.is_empty() {
        writeln!(out)?;
        writeln!(out, "{body}")?;
    }
    writeln!(out)?;
    Ok(())
}

/// Collapse blank runs and stop after [`BODY_LINES`], marking the cut.
fn compact_body(body: &str) -> String {
    let mut kept: Vec<&str> = Vec::new();
    let mut previous_blank = false;
    let mut truncated = false;
    for line in body.lines() {
        let blank = line.trim().is_empty();
        if blank && (previous_blank || kept.is_empty()) {
            continue;
        }
        if kept.len() >= BODY_LINES {
            truncated = true;
            break;
        }
        kept.push(line);
        previous_blank = blank;
    }
    while kept.last().map(|l| l.trim().is_empty()).unwrap_or(false) {
        kept.pop();
    }
    let mut text = kept.join("\n");
    if truncated {
        text.push_str("\n(...)");
    }
    text
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::DEFAULT_PREFIX;
    use crate::ops::{create, CreateOpts};
    use std::fs;

    fn seeded_layout() -> (tempfile::TempDir, Layout) {
        let dir = tempfile::tempdir().unwrap();
        let layout = Layout::new(dir.path(), DEFAULT_PREFIX);
        fs::create_dir_all(layout.projects_dir()).unwrap();
        create(
            &layout,
            "alpha",
            "wire the parser",
            CreateOpts {
                priority: Some('A'),
                tags: Some("parser,core"),
                body: Some("Scope: the front end.\n\n\nDone-when: it round-trips."),
                ..Default::default()
            },
        )
        .unwrap();
        create(&layout, "beta", "other project work", CreateOpts::default()).unwrap();
        (dir, layout)
    }

    #[test]
    fn org_mirror_carries_the_banner_and_selected_projects_only() {
        let (_dir, layout) = seeded_layout();
        let text = render(&layout, &["alpha".to_string()], Format::Org, None).unwrap();
        assert!(
            text.contains("# MIRROR: generated by `vissue mirror`"),
            "{text}"
        );
        assert!(text.contains("# Projects: alpha"), "{text}");
        assert!(text.contains("* alpha"), "{text}");
        assert!(!text.contains("* beta"), "{text}");
        assert!(text.contains("** TODO [#A] wire the parser"), "{text}");
        assert!(text.contains(":TAGS: parser,core"), "{text}");
        assert!(text.contains("Scope: the front end."), "{text}");
    }

    #[test]
    fn an_empty_project_list_covers_every_project() {
        let (_dir, layout) = seeded_layout();
        let text = render(&layout, &[], Format::Org, None).unwrap();
        assert!(text.contains("* alpha"), "{text}");
        assert!(text.contains("* beta"), "{text}");
        assert!(text.contains("# Projects: alpha, beta"), "{text}");
    }

    #[test]
    fn the_mirror_reparses_as_issue_headings() {
        let (_dir, layout) = seeded_layout();
        let text = render(&layout, &[], Format::Org, None).unwrap();
        // Level-two mirror headings are not top-level issues, so a reparse of
        // the projection finds the project headings and no issue bodies.
        let doc = IssueDoc::parse("mirror", std::path::PathBuf::from("/tmp/m.org"), &text);
        assert!(doc.is_err(), "project headings carry no :ID: property");
    }

    #[test]
    fn markdown_mirror_lists_metadata_as_bullets() {
        let (_dir, layout) = seeded_layout();
        let text = render(&layout, &["alpha".to_string()], Format::Markdown, None).unwrap();
        assert!(text.contains("### TODO [#A] wire the parser"), "{text}");
        assert!(text.contains("- tags: parser,core"), "{text}");
    }

    #[test]
    fn state_filter_selects_a_single_bucket() {
        let (_dir, layout) = seeded_layout();
        let text = render(&layout, &[], Format::Org, Some("DONE")).unwrap();
        assert!(!text.contains("** TODO"), "{text}");
        assert!(text.contains("# Projects: alpha, beta"), "{text}");
    }

    #[test]
    fn body_compaction_collapses_blanks_and_marks_the_cut() {
        let long: String = (1..=20).map(|i| format!("line {i}\n")).collect();
        let compacted = compact_body(&long);
        assert_eq!(compacted.lines().count(), BODY_LINES + 1);
        assert!(compacted.ends_with("(...)"), "{compacted}");
        assert_eq!(compact_body("a\n\n\n\nb"), "a\n\nb");
        assert_eq!(compact_body("\n\n"), "");
    }

    #[test]
    fn format_parsing_rejects_unknown_names() {
        assert_eq!(Format::parse("org").unwrap(), Format::Org);
        assert_eq!(Format::parse("md").unwrap(), Format::Markdown);
        assert!(Format::parse("pdf").is_err());
    }
}
