//! A read-only projection of selected projects into a single shareable file.
//!
//! The mirror exists so a collaborator who cannot reach the tracker still sees
//! the backlog. It carries a banner naming it as generated output, because the
//! next run overwrites it and hand edits are lost.

use anyhow::{bail, Result};
use std::fmt::Write as _;

use crate::config::Layout;
use crate::model::{today_inactive_bracket, IssueHeading, TODO_HEADER};
use crate::store::{list_projects, IssueDoc};

/// Body lines carried into the projection before it is cut short.
pub const BODY_LINES: usize = 12;

const BANNER: &str =
    "MIRROR: generated by `vissue mirror`. Read-only projection; edits here are overwritten.";

/// Output shape for [`render`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Format {
    Org,
    Markdown,
}

impl Format {
    pub fn parse(s: &str) -> Result<Self> {
        match s {
            "org" => Ok(Format::Org),
            "markdown" | "md" => Ok(Format::Markdown),
            other => bail!("unknown format {other:?}; allowed: org, markdown"),
        }
    }
}

/// Project the named projects into one document. An empty `projects` list
/// covers every project in the layout.
pub fn render(
    layout: &Layout,
    projects: &[String],
    format: Format,
    state_filter: Option<&str>,
) -> Result<String> {
    let selected: Vec<String> = if projects.is_empty() {
        list_projects(layout)?
    } else {
        let mut v = projects.to_vec();
        v.sort();
        v.dedup();
        v
    };

    let mut out = String::new();
    match format {
        Format::Org => {
            writeln!(out, "#+TITLE: vissue mirror")?;
            writeln!(out, "#+DATE: {}", today_inactive_bracket())?;
            writeln!(out, "#+FILETAGS: :vissue:mirror:")?;
            writeln!(out, "{TODO_HEADER}")?;
            writeln!(out, "# {BANNER}")?;
            writeln!(out, "# Projects: {}", selected.join(", "))?;
            writeln!(out)?;
        }
        Format::Markdown => {
            writeln!(out, "# vissue mirror")?;
            writeln!(out)?;
            writeln!(out, "_{BANNER}_")?;
            writeln!(out)?;
            writeln!(
                out,
                "Generated {} for: {}",
                today_inactive_bracket(),
                selected.join(", ")
            )?;
            writeln!(out)?;
        }
    }

    for project in &selected {
        let path = layout.project_issues_path(project);
        let doc = IssueDoc::parse_file(project, &path)?;
        let mut headings: Vec<&IssueHeading> = doc
            .headings
            .iter()
            .filter(|h| state_filter.map(|s| h.state == s).unwrap_or(true))
            .collect();
        headings.sort_by(|a, b| {
            a.priority
                .cmp(&b.priority)
                .then_with(|| a.state.cmp(&b.state))
                .then_with(|| a.id.cmp(&b.id))
        });
        if headings.is_empty() {
            continue;
        }
        match format {
            Format::Org => {
                writeln!(out, "* {project}")?;
                for h in headings {
                    render_org_issue(&mut out, h)?;
                }
            }
            Format::Markdown => {
                writeln!(out, "## {project}")?;
                writeln!(out)?;
                for h in headings {
                    render_markdown_issue(&mut out, h)?;
                }
            }
        }
    }
    Ok(out)
}

/// Issues render at level two, so a body heading has to sit at level three or
/// deeper. Without the shift, a body that opens with `** Scope` becomes a
/// sibling of the issues and the projection's outline is wrong.
const ISSUE_LEVEL: usize = 2;

fn render_org_issue(out: &mut String, h: &IssueHeading) -> Result<()> {
    writeln!(out, "** {} [#{}] {}", h.state, h.priority, h.title)?;
    writeln!(out, ":PROPERTIES:")?;
    writeln!(out, "{}", property_line("ID", &h.id))?;
    for key in [
        "PARENT",
        "BLOCKED_BY",
        "TAGS",
        "DEADLINE",
        "TYPE",
        "CLAIMED_BY",
        "CLAIMED_AT",
    ] {
        if let Some(val) = h.properties.get(key) {
            writeln!(out, "{}", property_line(key, val))?;
        }
    }
    writeln!(out, ":END:")?;
    let body = demote_headings(&compact_body(&h.body));
    if !body.is_empty() {
        writeln!(out)?;
        writeln!(out, "{body}")?;
    }
    Ok(())
}

/// `:KEY:` padded to the column the tracker's own writer uses.
fn property_line(key: &str, value: &str) -> String {
    let name = format!(":{key}:");
    let pad = 13usize.saturating_sub(name.len()).max(1);
    format!("{name}{}{value}", " ".repeat(pad))
}

/// Push every heading in a body below the issue that owns it, preserving the
/// relative nesting the author wrote.
fn demote_headings(body: &str) -> String {
    let shallowest = body
        .lines()
        .filter_map(heading_level)
        .min()
        .unwrap_or(usize::MAX);
    if shallowest > ISSUE_LEVEL {
        return body.to_string();
    }
    let shift = ISSUE_LEVEL + 1 - shallowest;
    body.lines()
        .map(|line| {
            if heading_level(line).is_some() {
                format!("{}{}", "*".repeat(shift), line)
            } else {
                line.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// The number of leading stars, when the line is an org heading.
fn heading_level(line: &str) -> Option<usize> {
    let stars = line.chars().take_while(|c| *c == '*').count();
    if stars > 0 && line.chars().nth(stars) == Some(' ') {
        Some(stars)
    } else {
        None
    }
}

fn render_markdown_issue(out: &mut String, h: &IssueHeading) -> Result<()> {
    writeln!(out, "### {} [#{}] {}", h.state, h.priority, h.title)?;
    writeln!(out)?;
    writeln!(out, "- id: `{}`", h.id)?;
    for key in [
        "PARENT",
        "BLOCKED_BY",
        "TAGS",
        "DEADLINE",
        "TYPE",
        "CLAIMED_BY",
        "CLAIMED_AT",
    ] {
        if let Some(val) = h.properties.get(key) {
            writeln!(out, "- {}: {}", key.to_lowercase(), val)?;
        }
    }
    let body = compact_body(&h.body);
    if !body.is_empty() {
        writeln!(out)?;
        writeln!(out, "{body}")?;
    }
    writeln!(out)?;
    Ok(())
}

/// Collapse blank runs and stop after [`BODY_LINES`], marking the cut.
fn compact_body(body: &str) -> String {
    let mut kept: Vec<&str> = Vec::new();
    let mut previous_blank = false;
    let mut truncated = false;
    for line in body.lines() {
        let blank = line.trim().is_empty();
        if blank && (previous_blank || kept.is_empty()) {
            continue;
        }
        if kept.len() >= BODY_LINES {
            truncated = true;
            break;
        }
        kept.push(line);
        previous_blank = blank;
    }
    while kept.last().map(|l| l.trim().is_empty()).unwrap_or(false) {
        kept.pop();
    }
    let mut text = kept.join("\n");
    if truncated {
        text.push_str("\n(...)");
    }
    text
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::DEFAULT_PREFIX;
    use crate::ops::{create, CreateOpts};
    use std::fs;

    fn seeded_layout() -> (tempfile::TempDir, Layout) {
        let dir = tempfile::tempdir().unwrap();
        let layout = Layout::new(dir.path(), DEFAULT_PREFIX);
        fs::create_dir_all(layout.projects_dir()).unwrap();
        create(
            &layout,
            "alpha",
            "wire the parser",
            CreateOpts {
                priority: Some('A'),
                tags: Some("parser,core"),
                body: Some("Scope: the front end.\n\n\nDone-when: it round-trips."),
                ..Default::default()
            },
        )
        .unwrap();
        create(&layout, "beta", "other project work", CreateOpts::default()).unwrap();
        (dir, layout)
    }

    #[test]
    fn org_mirror_carries_the_banner_and_selected_projects_only() {
        let (_dir, layout) = seeded_layout();
        let text = render(&layout, &["alpha".to_string()], Format::Org, None).unwrap();
        assert!(
            text.contains("# MIRROR: generated by `vissue mirror`"),
            "{text}"
        );
        assert!(text.contains("# Projects: alpha"), "{text}");
        assert!(text.contains("* alpha"), "{text}");
        assert!(!text.contains("* beta"), "{text}");
        assert!(text.contains("** TODO [#A] wire the parser"), "{text}");
        assert!(text.contains(":TAGS:       parser,core"), "{text}");
        assert!(text.contains("Scope: the front end."), "{text}");
    }

    #[test]
    fn an_empty_project_list_covers_every_project() {
        let (_dir, layout) = seeded_layout();
        let text = render(&layout, &[], Format::Org, None).unwrap();
        assert!(text.contains("* alpha"), "{text}");
        assert!(text.contains("* beta"), "{text}");
        assert!(text.contains("# Projects: alpha, beta"), "{text}");
    }

    #[test]
    fn the_mirror_reparses_as_issue_headings() {
        let (_dir, layout) = seeded_layout();
        let text = render(&layout, &[], Format::Org, None).unwrap();
        // Level-two mirror headings are not top-level issues, so a reparse of
        // the projection finds the project headings and no issue bodies.
        let doc = IssueDoc::parse("mirror", std::path::PathBuf::from("/tmp/m.org"), &text);
        assert!(doc.is_err(), "project headings carry no :ID: property");
    }

    #[test]
    fn markdown_mirror_lists_metadata_as_bullets() {
        let (_dir, layout) = seeded_layout();
        let text = render(&layout, &["alpha".to_string()], Format::Markdown, None).unwrap();
        assert!(text.contains("### TODO [#A] wire the parser"), "{text}");
        assert!(text.contains("- tags: parser,core"), "{text}");
    }

    #[test]
    fn state_filter_selects_a_single_bucket() {
        let (_dir, layout) = seeded_layout();
        let text = render(&layout, &[], Format::Org, Some("DONE")).unwrap();
        assert!(!text.contains("** TODO"), "{text}");
        assert!(text.contains("# Projects: alpha, beta"), "{text}");
    }

    #[test]
    fn body_compaction_collapses_blanks_and_marks_the_cut() {
        let long: String = (1..=20).map(|i| format!("line {i}\n")).collect();
        let compacted = compact_body(&long);
        assert_eq!(compacted.lines().count(), BODY_LINES + 1);
        assert!(compacted.ends_with("(...)"), "{compacted}");
        assert_eq!(compact_body("a\n\n\n\nb"), "a\n\nb");
        assert_eq!(compact_body("\n\n"), "");
    }

    #[test]
    fn body_headings_sit_below_the_issue_that_owns_them() {
        // A body written with level-two headings would otherwise render as a
        // sibling of the issues, so the outline would claim Scope is an issue.
        assert_eq!(
            demote_headings("** Scope\ntext\n*** Detail"),
            "*** Scope\ntext\n**** Detail"
        );
        assert_eq!(demote_headings("* Top\n** Under"), "*** Top\n**** Under");
        assert_eq!(
            demote_headings("**** Already deep"),
            "**** Already deep",
            "a body that is already nested is left alone"
        );
        assert_eq!(demote_headings("no headings here"), "no headings here");
        assert_eq!(
            demote_headings("*bold* not a heading"),
            "*bold* not a heading",
            "a star without a following space is not a heading"
        );
    }

    #[test]
    fn a_mirrored_body_heading_never_reparses_as_an_issue() {
        let dir = tempfile::tempdir().unwrap();
        let layout = Layout::new(dir.path(), DEFAULT_PREFIX);
        fs::create_dir_all(layout.projects_dir()).unwrap();
        create(
            &layout,
            "alpha",
            "structured body",
            CreateOpts {
                body: Some("** Scope\nthe front end.\n** Done when\nit round-trips."),
                ..Default::default()
            },
        )
        .unwrap();
        let text = render(&layout, &[], Format::Org, None).unwrap();
        assert!(text.contains("*** Scope"), "{text}");
        assert!(text.contains("*** Done when"), "{text}");
        assert!(
            !text.contains("\n** Scope"),
            "a body heading kept issue level: {text}"
        );
    }

    #[test]
    fn property_lines_line_up_with_the_tracker_format() {
        assert_eq!(property_line("ID", "alpha-1a2b"), ":ID:         alpha-1a2b");
        assert_eq!(
            property_line("PARENT", "alpha-9z8y"),
            ":PARENT:     alpha-9z8y"
        );
        assert_eq!(
            property_line("BLOCKED_BY", "alpha-1"),
            ":BLOCKED_BY: alpha-1"
        );
    }

    #[test]
    fn format_parsing_rejects_unknown_names() {
        assert_eq!(Format::parse("org").unwrap(), Format::Org);
        assert_eq!(Format::parse("md").unwrap(), Format::Markdown);
        assert!(Format::parse("pdf").is_err());
    }
}
